name: prototype
breakdown:
  model: gpt-4o-mini
  system_prompt: source-breakdown-system-prompt.md
script:
  model: gpt-4o-mini
  system_prompt: short-script-system-prompt.md
  temperature: 1.0
chunk:
  model: gpt-4o-mini
  system_prompt: transcript-chunker-system-prompt.md
image:
  model: bytedance/hyper-flux-8step:16084e9731223a4367228928a6cb393b21736da2a0ca6a5a492ce311f0a97143
voice:
  backend: readaloud