# generated by datamodel-codegen:
#   filename:  api.schema.json
#   timestamp: 2026-03-29T20:52:44+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, RootModel


class Section(Enum):
    Hook = 'Hook'
    Body = 'Body'
    Close = 'Close'


class Scene(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    imagery: str
    section: Section
    image_path: str | None = None
    voice_path: str | None = None


class Chunks(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scenes: list[Scene]
    title: str | None = None
    description: str | None = None


class SourceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chapter: str | None = None
    section: str | None = None
    timestamp: str | None = None


class Nugget(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    title: str
    start_line: float
    end_line: float
    source_ref: SourceRef | None = None
    original_text: str | None = None
    cache_key: str | None = None
    word_count: float | None = None


class ApiSchemas(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    chunks: Chunks | None = None
    nugget: Nugget | None = None


class Model(RootModel[ApiSchemas]):
    root: ApiSchemas
