# generated by datamodel-codegen:
#   filename:  progress-event-type.schema.json
#   timestamp: 2026-03-15T04:39:36+00:00

from __future__ import annotations

from enum import Enum

from pydantic import RootModel


class ProgressEventType(Enum):
    breakdown_started = 'breakdown_started'
    breakdown_completed = 'breakdown_completed'
    video_started = 'video_started'
    script_created = 'script_created'
    video_completed = 'video_completed'
    initial_processing_complete = 'initial_processing_complete'
    feedback_partial = 'feedback_partial'
    feedback_completed = 'feedback_completed'
    asset_gen_started = 'asset_gen_started'
    image_generated = 'image_generated'
    voice_generated = 'voice_generated'
    caption_generated = 'caption_generated'
    asset_gen_completed = 'asset_gen_completed'
    error = 'error'


class Model(RootModel[ProgressEventType]):
    root: ProgressEventType
