# generated by datamodel-codegen:
#   filename:  progress-event-type.schema.json
#   timestamp: 2026-03-14T08:27:22+00:00

from __future__ import annotations

from enum import Enum

from pydantic import RootModel


class ProgressEventType(Enum):
    breakdown_started = 'breakdown_started'
    breakdown_complete = 'breakdown_complete'
    clip_complete = 'clip_complete'
    initial_processing_complete = 'initial_processing_complete'
    feedback_applied = 'feedback_applied'
    finalize_progress = 'finalize_progress'
    finalize_complete = 'finalize_complete'
    error = 'error'
    PROGRESS = 'PROGRESS'
    VIDEO_CREATED = 'VIDEO_CREATED'
    VIDEO_READY = 'VIDEO_READY'


class Model(RootModel[ProgressEventType]):
    root: ProgressEventType
