# generated by datamodel-codegen:
#   filename:  progress-event-type.schema.json
#   timestamp: 2026-04-04T02:14:30+00:00

from __future__ import annotations

from enum import Enum

from pydantic import RootModel


class ProgressEventType(Enum):
    breakdown_started = 'breakdown_started'
    breakdown_completed = 'breakdown_completed'
    video_started = 'video_started'
    script_created = 'script_created'
    video_completed = 'video_completed'
    initial_processing_complete = 'initial_processing_complete'
    suggestion_started = 'suggestion_started'
    suggestion_partial = 'suggestion_partial'
    suggestion_completed = 'suggestion_completed'
    request_sent = 'request_sent'
    asset_gen_started = 'asset_gen_started'
    asset_gen_progress = 'asset_gen_progress'
    image_uploaded = 'image_uploaded'
    voice_uploaded = 'voice_uploaded'
    caption_generated = 'caption_generated'
    asset_gen_completed = 'asset_gen_completed'
    error = 'error'


class Model(RootModel[ProgressEventType]):
    root: ProgressEventType
