# generated by datamodel-codegen:
#   filename:  table.schema.json
#   timestamp: 2026-03-29T20:52:44+00:00

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, RootModel


class Run(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    userId: str
    user_input: str
    title: str | None
    status: str | None
    breakdown_messages: str | None
    script_regen_count: float | None
    created_at: Any | str | None = None


class Video(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    run_id: UUID
    s3_prefix: str | None
    render_id: str | None
    source_text: str | None
    status: str | None
    script: str | None
    chunks: str | None
    cache_key: str | None
    config_hash: str | None
    brand_id: UUID | None
    created_at: Any | str | None = None


class Brand(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: UUID
    userId: str
    created_at: Any | str | None = None
    style_prompt: str | None
    mascot_description: str | None
    avatar_s3_key: str | None


class TableSchemas(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    run: Run | None = None
    video: Video | None = None
    brand: Brand | None = None


class Model(RootModel[TableSchemas]):
    root: TableSchemas
