# generated by datamodel-codegen:
#   filename:  manifest.schema.json
#   timestamp: 2026-03-15T04:39:35+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel


class Scene(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    imagePath: str
    voicePath: str
    durationInSeconds: float
    imageWidth: float | None = None
    imageHeight: float | None = None


class Caption(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    text: str
    startMs: float
    endMs: float
    timestampMs: float | None
    confidence: float | None


class VideoManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cacheKey: str
    fps: float
    width: float
    height: float
    durationInFrames: float
    scenes: list[Scene]
    captions: list[Caption]


class Model(RootModel[VideoManifest]):
    root: VideoManifest
