/**
 * SST config types for sst.config.ts.
 * Provides $config and sst globals until .sst/platform/config.d.ts is generated by `sst dev`.
 */
declare global {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const sst: any;
  // AWS provider is preloaded by SST
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const aws: any;
  function $config(input: {
    app?: (input: { stage: string }) => { name: string; home?: "aws" | "cloudflare" | "local" };
    run?: () => Promise<Record<string, unknown> | void>;
    console?: Record<string, unknown>;
  }): unknown;
}

export {};
