name: prototype
breakdown:
  model: gpt-4o-mini
  system_prompt: source-breakdown-system-prompt.md
script:
  model: gpt-4o-mini
  system_prompt: short-script-system-prompt.md
  temperature: 1.0
chunk:
  model: gpt-4o-mini
  system_prompt: transcript-chunker-system-prompt.md