/**
 * Sample content for inspiration cards. Sourced from source/random/.
 */

export const YOUTUBE_SAMPLE = `this video is sponsored by Squarespace   go to Squarespace com Sasha the plain   bagel to save 10% off your first   purchase of a website or domain using   code the plain bagel if I were to ask   you about stock trading this would   probably be the image that comes to mind   the New York Stock Exchange trading   floor a scene synonymous with stock   investing itself this is where traders   meet in person to buy and sell stocks   finding deals for their clients and   employers and yelling tickers and prices   across the trading floor well this used   to be how most trading was done these   days you can do most of the work online   in advancements in technology have even   allowed everyday individuals to take up   trading at home to try and make money   but despite the fact that trading   involves stocks and other investments it   is often seen as a very different   practice from investing what you or I   probably do when we buy or sell stocks   you see being a trader   whether professionally or as a hobby is   different from being an investor and   while you've probably heard of people   making quite a bit of money off trading   it's an area that most people are best   served avoiding why will answer that   question and more on today's plain bagel`;

export const ARTICLE_SAMPLE = `The compounding effect in financial terms refers to the process where an investment generates earnings, and those earnings are reinvested to generate their own earnings over time. Instead of growing in a straight line, money grows exponentially because each period's returns build on the previous total. For example, if you invest $10,000 at a 7% annual return, you don't just earn 7% on the original $10,000 each year — you earn 7% on the growing balance, including past interest. Over long periods, this snowball effect can dramatically increase wealth, which is why starting early and staying invested are often more important than trying to time the market!`;

export const BOOK_SAMPLE = `You are my favorite writer.   >> Thank you.   >> You have the most insights per word of   anybody that's writing stuff at the   moment.   >> Well, thanks. That that means a lot to   me. Thank you.   >> You could have chosen to write about   anything.   Why choose to write about spending   money?   Well, I I'll take it back to the start   of my career, which was like a lot of   young men, particularly in the in the   mid 2000s.

 Uh the ultimate goal before   tech really existed, the ultimate goal   was be an investment banker on Wall   Street. And it's hard to remember that   era because now if you're a young person   at Stanford or whatever, your goal is   like go work at Google, go work at at at   OpenAI. Back then it was all go work at   Goldman Sachs.

 And so what my my sole   kind of life aspiration when I was 20   was to be an investment banker or a   hedge fund manager.   >> And I knew I I loved investing even at   that age. I used to go to Barnes & Noble   and read investing books and I loved it   to begin with. I just I was fascinated   with money.   >> And then I haphazardly got a job as a   writer because I graduated in 2008.

 The   economy was was a wreck and nobody was   hiring. No banks were hiring. And so the   only finance job that I could find was   as a writer for the monthly fool. Didn't   want to be a writer. Hated writing. Was   embarrassed that I had dreams to be a   powerful investment banker. And now I   was a journalist.`;
