/**
 * Drizzle schema for Auth.js (NextAuth) and app tables.
 * Used by apps/web via @shortgen/db.
 * Exports Zod schemas via drizzle-zod for types/table and Python codegen.
 */

import { relations } from "drizzle-orm";
import {
  integer,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { createSelectSchema } from "drizzle-zod";
import { z } from "zod";

// Table prefix (change here to rename all tables)
const TABLE_PREFIX = "shortgen_";
const t = (name: string) => `${TABLE_PREFIX}${name}`;

// Auth.js tables (see https://authjs.dev/getting-started/adapters/drizzle)

export const user = pgTable(t("user"), {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => crypto.randomUUID()),
  name: text("name"),
  email: text("email").unique(),
  emailVerified: timestamp("emailVerified", { mode: "date" }),
  image: text("image"),
  /** Stripe customer ID for subscriptions and one-time purchases. */
  stripeCustomerId: text("stripeCustomerId"),
});

export const account = pgTable(
  t("account"),
  {
    userId: text("userId")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    provider: text("provider").notNull(),
    providerAccountId: text("providerAccountId").notNull(),
    refresh_token: text("refresh_token"),
    access_token: text("access_token"),
    expires_at: integer("expires_at"),
    token_type: text("token_type"),
    scope: text("scope"),
    id_token: text("id_token"),
    session_state: text("session_state"),
  },
  (account) => [
    primaryKey({
      columns: [account.provider, account.providerAccountId],
    }),
  ],
);

export const session = pgTable(t("session"), {
  sessionToken: text("sessionToken").primaryKey(),
  userId: text("userId")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  expires: timestamp("expires", { mode: "date" }).notNull(),
});

export const verificationToken = pgTable(
  t("verification_token"),
  {
    identifier: text("identifier").notNull(),
    token: text("token").notNull(),
    expires: timestamp("expires", { mode: "date" }).notNull(),
  },
  (vt) => [primaryKey({ columns: [vt.identifier, vt.token] })],
);

// Run-Video flow: one run (source text) can have many videos
// Keys match DB column names (snake_case) for consistency with Python and drizzle-zod output.
// Run status = pipeline phase: breakdown → scripting → asset_gen → export
// Video-level: exporting/exported (run stays "export" when Export clicked)
export const runStatusValues = [
  "breakdown",
  "scripting",
  "asset_gen",
  "export",
  "failed",
] as const;
export type RunStatus = (typeof runStatusValues)[number];

export const RUN_PHASE_STEPS: { key: RunStatus; label: string }[] = [
  { key: "breakdown", label: "Processing" },
  { key: "scripting", label: "Review" },
  { key: "asset_gen", label: "Generate" },
  { key: "export", label: "Export" },
];

export const runs = pgTable(t("runs"), {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("userId")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  user_input: text("user_input").notNull(),
  /** Short display title for the run. Generated by gpt-4o-mini alongside breakdown_messages. */
  title: text("title"),
  status: text("status").$type<RunStatus>().default("breakdown"),
  /** JSON array of playful loading messages for breakdown phase. Generated by gpt-4o-mini. */
  breakdown_messages: text("breakdown_messages"),
  /** Script regeneration count for this run; free up to SCRIPT_REGEN_FREE_LIMIT. */
  script_regen_count: integer("script_regen_count").default(0),
  created_at: timestamp("created_at").defaultNow(),
});

export const videos = pgTable(t("videos"), {
  id: uuid("id").primaryKey().defaultRandom(),
  run_id: uuid("run_id")
    .notNull()
    .references(() => runs.id, { onDelete: "cascade" }),
  s3_prefix: text("s3_prefix"),
  source_text: text("source_text"), // Raw source chunk for this clip (nugget.original_text)
  status: text("status")
    .$type<"created" | "scripts" | "assets" | "exporting" | "exported" | "failed">()
    .default("created"),
  script: text("script"),
  chunks: text("chunks"), // JSON: Chunks from pipeline
  cache_key: text("cache_key"),
  config_hash: text("config_hash"),
  created_at: timestamp("created_at").defaultNow(),
});

export const runsRelations = relations(runs, ({ one, many }) => ({
  user: one(user, {
    fields: [runs.userId],
    references: [user.id],
  }),
  videos: many(videos),
}));

export const videosRelations = relations(videos, ({ one }) => ({
  run: one(runs, {
    fields: [videos.run_id],
    references: [runs.id],
  }),
}));

// Billing: tier from priceId
export const tierValues = ["free", "basic", "pro", "business"] as const;
export type Tier = (typeof tierValues)[number];

export const subscription = pgTable(t("subscription"), {
  userId: text("userId")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  stripeCustomerId: text("stripeCustomerId"),
  stripeSubscriptionId: text("stripeSubscriptionId"),
  priceId: text("priceId"),
  status: text("status").$type<
    "active" | "canceled" | "past_due" | "unpaid" | "trialing"
  >(),
  currentPeriodEnd: timestamp("currentPeriodEnd", { mode: "date" }),
  tier: text("tier").$type<Tier>().notNull().default("free"),
  created_at: timestamp("created_at").defaultNow(),
  updated_at: timestamp("updated_at").defaultNow(),
});

export const creditBalance = pgTable(t("credit_balance"), {
  userId: text("userId")
    .primaryKey()
    .references(() => user.id, { onDelete: "cascade" }),
  balance: integer("balance").notNull().default(0),
  updated_at: timestamp("updated_at").defaultNow(),
});

export const creditTransactionType = [
  "signup_bonus",
  "purchase",
  "usage",
  "subscription_grant",
] as const;
export type CreditTransactionType = (typeof creditTransactionType)[number];

export const creditTransaction = pgTable(t("credit_transaction"), {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("userId")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  amount: integer("amount").notNull(),
  type: text("type").$type<CreditTransactionType>().notNull(),
  reference: text("reference"),
  stripe_event_id: text("stripe_event_id").unique(),
  created_at: timestamp("created_at").defaultNow(),
});

// stripe_event_id unique: multiple NULLs allowed; non-NULL dedupes Stripe retries
// In Drizzle we'll add this via raw SQL in migration or use unique constraint on nullable column
// For now we rely on application-level check before insert

// Zod schemas for API validation and Python codegen (types:sync)
// Override timestamp fields to string for JSON Schema / Python compatibility
const timestampSchema = z.string().optional();
export const runSchema = createSelectSchema(runs, {
  created_at: timestampSchema,
});
export const videoSchema = createSelectSchema(videos, {
  created_at: timestampSchema,
});
export type Run = z.infer<typeof runSchema>;
export type Video = z.infer<typeof videoSchema>;
